service: mailchimp

provider:
  name: aws
  runtime: nodejs4.3
  region: ${file(./config.json):region}
  environment:
    MAILCHIMP_API_KEY: ${file(./config.json):MAILCHIMP_API_KEY}
    MAILCHIMP_REGION: ${file(./config.json):MAILCHIMP_REGION}
    DEFAULT_REDIRECT_URL: ${file(./config.json):DEFAULT_REDIRECT_URL}

functions:
  mailchimp:
    handler: handler.mailchimpService
    events:
      - http:
          path: mailchimp
          method: post
          cors: true
