service: hubspot-service

provider:
  name: aws
  runtime: nodejs6.10
  region: ${file(./config.json):region}
  stage: prod
  environment:
    HUBSPOT_API_KEY: ${file(./config.json):HUBSPOT_API_KEY}

functions:
  addContact:
    handler: handler.addContact
    events:
      - http:
          path: hubspot/add
          method: post
          cors: true
