
service: forum-new-user-processing

custom:
  stage: "${opt:stage, self:provider.stage}"
  region: "${opt:region, self:provider.region}"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SENDGRID_API_KEY: ${file(./config.json):SENDGRID_API_KEY}
    SERVERLESS_USER_API_ENDPOINT: ${file(./config.json):SERVERLESS_USER_API_ENDPOINT}
    SERVERLESS_USER_API_KEY: ${file(./config.json):SERVERLESS_USER_API_KEY}
    REF_URL_EXAMPLE: { "Fn::Join" : ["", [ "https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}" ] ]  }

functions:
  newForumUser:
    handler: handler.newForumUser
    events:
      - http:
          path: new-user
          method: post
          cors: true
