backend:
  name: serverless
  repo: serverless/site
  branch: master

media_folder: "content/assets"
public_folder: "content"

collections: # A list of collections the CMS should be able to edit
  - name: "company" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Company"
    folder: "content/learn"
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Photo", name: "cover", widget: "image", optional: true}
      - {label: "Contenu", name: "content", widget: "markdown"}
    meta:
      - {label: "Numéro", name: "number", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Langue", name: "locale", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image", optional: true}
