service: customerio-service

provider:
  name: aws
  runtime: nodejs6.10
  region: ${file(./config.json):region}
  stage: prod
  environment:
    CUSTOMER_IO_API_KEY: ${file(./config.json):CUSTOMER_IO_API_KEY}
    CUSTOMER_IO_SITE: ${file(./config.json):CUSTOMER_IO_SITE}

functions:
  track:
    handler: handler.track
    events:
      - http:
          path: track
          method: post
          cors: true
  identify:
    handler: handler.identify
    events:
      - http:
          path: identify
          method: post
          cors: true
