
service:
  name: growth-user-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2
  environment:
    AUTH0_DOMAIN: ${file(./config.json):AUTH0_DOMAIN}
    AUTH0_CLIENT_ID: ${file(./config.json):AUTH0_CLIENT_ID}
    AUTH0_CLIENT_SECRET: ${file(./config.json):AUTH0_CLIENT_SECRET}
    SECRET_ACCESS_KEY: ${file(./config.json):SECRET_ACCESS_KEY}

functions:
  authenticate:
    handler: handler.authenticate
  getUserByEmail:
    handler: handler.getUserByEmail
    events:
      - http:
          path: users-by-email
          method: post
          authorizer: authenticate
          cors: true
